language: python
sudo: false

python:
  - "2.7"

addons:
  apt:
    packages:
    - python-pexpect
    - xsltproc
    - time

before_install:
  - pip install suds
  - pip install pycurl
  - pip install requests
  - pip install pexpect

script:
  - ./autogen.sh
  - ./configure
  - make
  - make check
