language: python
sudo: false

python:
  - "2.6"

addons:
  apt:
    packages:
    - python-pexpect
    - xsltproc
    - time
    - libnet-telnet-perl

before_install:
  - pip install suds
  - pip install pycurl
  - pip install requests
  - pip install pexpect=2.3

script:
  - ./autogen.sh
  - ./configure --with-agents='apc apc_snmp bladecenter brocade cisco_mds cisco_ucs drac5 eaton_snmp emerson eps hpblade ibmblade ifmib ilo ilo_moonshot ilo_mp ilo_ssh intelmodular ipdu ipmilan mpath kdump rhevm rsa rsb scsi vmware_soap wti virsh'
  - make
  - make check
