language: python
sudo: required

python:
  - "2.7"

addons:
  apt:
    packages:
    - python-pexpect
    - xsltproc
    - time
    - libpam0g-dev
    - libcimcclient0-dev

before_install:
  - pip install suds
  - pip install pycurl
  - pip install requests
  - pip install pexpect

before_script:
  - wget https://github.com/Openwsman/openwsman/archive/v2.6.2.tar.gz -O /tmp/openwsman-2.6.2.tar.gz
  - tar zxvf /tmp/openwsman-2.6.2.tar.gz
  - cd openwsman-2.6.2
  - mkdir build && cd build
  - cmake ..
  - make
  - sudo make install

script:
  - ./autogen.sh
  - ./configure
  - make
  - make check
  - PYTHONPATH=fence/agents/lib python fence/agents/lib/tests/test_fencing.py
